apiVersion: v1
kind: Service
metadata:
  name: resources-service
  namespace: k8s-program-m1
spec:
  type: NodePort
  selector:
    app: resources-service-pod
  ports:
    - name: http
      port: 8082
      targetPort: 8080
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-service
  namespace: k8s-program-m1
spec:
  selector:
    matchLabels:
      app: resources-service-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: resources-service-pod
    spec:
      containers:
        - name: resources-service-app
          image: microservices-k8s/resources-service:1.0.2
          imagePullPolicy: Never
          resources:
            requests:
              memory: "250Mi"
            limits:
              memory: "500Mi"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: resources-service-vars
