apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-songs
  namespace: k8s-program-m1
spec:
  serviceName: postgres-songs
  replicas: 1
  selector:
    matchLabels:
      app: postgres-songs
  template:
    metadata:
      labels:
        app: postgres-songs
    spec:
      containers:
        - name: postgres-songs
          image: postgres:15
          ports:
            - containerPort: 5432
              name: postgres-songs
          envFrom:
            - configMapRef:
                name: postgres-vars
          volumeMounts:
            - name: postgres-data-songs
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data-songs
        namespace: k8s-program-m1
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi