apiVersion: v1
kind: Service
metadata:
  name: postgres-rs
  namespace: k8s-program-m1
spec:
#  type: ClusterIP
  selector:
    app: postgres-rs
  ports:
    - protocol: TCP
      port: 5433
      targetPort: 5432