apiVersion: v1
kind: PersistentVolume
metadata:
  name: songs-service-pv
  namespace: k8s-program-m1
  labels:
    app: songs-service-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: <local_path>/mnt/data/songs-service