apiVersion: v1
kind: Service
metadata:
  name: songs-service
  namespace: k8s-program-m1
spec:
  type: NodePort
  selector:
    app: songs-service-pod
  ports:
    - name: http
      port: 8083
      targetPort: 8081
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: songs-service
  namespace: k8s-program-m1
spec:
  selector:
    matchLabels:
      app: songs-service-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: songs-service-pod
    spec:
      containers:
        - name: songs-service-app
          image: microservices-k8s/songs-service:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: songs-service-volume
              mountPath: /app/data
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "750Mi"
          envFrom:
            - configMapRef:
                name: songs-service-vars
      volumes:
        - name: songs-service-volume
          persistentVolumeClaim:
            claimName: songs-service-pvc