apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-rs
  namespace: k8s-program-m1
spec:
  serviceName: postgres-rs
  replicas: 1
  selector:
    matchLabels:
      app: postgres-rs
  template:
    metadata:
      labels:
        app: postgres-rs
    spec:
      containers:
        - name: postgres-rs
          image: postgres:15
          ports:
            - containerPort: 5432
              name: postgres-rs
          envFrom:
            - configMapRef:
                name: postgres-vars
          volumeMounts:
            - name: postgres-data-rs
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data-rs
        namespace: k8s-program-m1
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi