apiVersion: v1
kind: Service
metadata:
  name: postgres-songs
  namespace: k8s-program-m1
spec:
  selector:
    app: postgres-songs
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432