apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: songs-service-pvc
  namespace: k8s-program-m1
  labels:
     app: songs-service-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""